---
title: "Serial Dilution and Feed Preparation"
subtitle: "Example"
author: "Sam Widmayer"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    css: drug.dilution.style.css
---

```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(knitr)
library(plyr)
library(kableExtra)
# opts_knit$set(root.dir=normalizePath('../'))
setwd("~/Documents/projects/NemaDose/") # Set to repo directory
options(knitr.table.format = "html") 
options(width = 10000)
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
compound.sheet <- read.csv("drug_stock_sheet.csv")
```

```{r echo=FALSE}
Strains = 1
Reps = 8
N_Doses = 6
N_Bleaches = 3
N_Wells = Strains*Reps*N_Doses*N_Bleaches
Excess_Percent = 10

########################################################
## Specify compounds of interest (remember spelling!) ##
########################################################
ChosenDrugList = c("Parathion", 
                   "2,4-D", 
                   "Arsenic trioxide", 
                   "Atrazine", 
                   "Carboxin", 
                   "Deltamethrin", 
                   "Permethrin", 
                   "Propoxur")
pre.DrugList <- compound.sheet %>%
  dplyr::select(Drug, DilutionFactors) %>%
  dplyr::filter(Drug %in% ChosenDrugList)
DrugList <- as.vector(pre.DrugList$Drug)
DilutionFactors = as.vector(pre.DrugList$DilutionFactors)
#####

##############################################################
## Read in highest dosing concentration from compound sheet ##
##############################################################
pre.HighDoseList <- compound.sheet %>%
  dplyr::filter(Drug %in% ChosenDrugList) %>%
  dplyr::select(High_Dose_uM)
High_Dose_List_uM <- as.vector(pre.HighDoseList$High_Dose_uM)
#####

##########################################################
## Read in drug stock concentration from compound sheet ##
##########################################################
pre.StockList <- compound.sheet %>%
  dplyr::filter(Drug %in% ChosenDrugList) %>%
  dplyr::select(Drug_Stock_Concentration_mM)
Drug_Stock_Concentration_mM <- as.vector(pre.StockList$Drug_Stock_Concentration_mM)
#####


Drugs = length(DrugList)
DrugDilutionList <- list(DrugList,
                         High_Dose_List_uM, 
                         Drug_Stock_Concentration_mM, 
                         DilutionFactors)
OD30totalvolume <- N_Wells*Drugs*25*(1+(Excess_Percent/100))
OD100totalvolume <- OD30totalvolume*0.3 #uL
n_conicals <- round(OD100totalvolume*0.001/7.5, digits = 0) # mL
n_microcentrifuge <- ((OD100totalvolume*0.001/7.5) - round(OD100totalvolume*0.001/7.5, digits = 0))/0.8 # ? not clear to Tim C. 20200611 are these 800 uL?
n_microcentrifuge_test <- OD100totalvolume - n_conicals*7500
n_microcentrifuge <- ifelse(n_microcentrifuge < 0, 0, n_microcentrifuge)
```
### Experimental Factors:
#### ```r N_Bleaches``` Independent Bleach(es)
#### ```r Strains``` Strains
#### ```r N_Doses``` Doses of ```r Drugs``` Compounds
#### ```r Reps``` Replicates of each Dose per Strain
#### ```r Excess_Percent```% Excess Accounted for in Design
#### Chosen Dilution Factors:
```{r echo=FALSE}
df.dat <- data.frame(DrugList, DilutionFactors)
colnames(df.dat) <- c("Compound", "Dilution Factor")
df.dat %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(full_width = F, position = "left")
```

<!-- ### Experiment requires ```r n_conicals``` 15 mL conicals and ```r n_microcentrifuge``` microcentrifuge tubes of OD100 HB101.  -->
### Experiment requires ```r OD100totalvolume*0.001``` mL OD100 HB101.
#### OD30 Preparation
##### 1) Add ```r OD100totalvolume*0.001``` mL OD100 HB101 to sterile tube.
##### 2) Add ```r (OD100totalvolume*0.001)/0.3 - (OD100totalvolume*0.001)``` mL K-media to sterile tube.
##### 3) Add ```r (150*OD30totalvolume)/80000``` microliters 80 mM kanamycin stock to sterile tube.

```{r echo=FALSE}
drug <- DrugList
high_dose <- High_Dose_List_uM
stock <- Drug_Stock_Concentration_mM
df <- DilutionFactors

drugdilutiontable <- list()
serialdilutiontable <- list()
fooddoses <- list()

for(i in 1:length(drug)){
## At what concentration should the drug be added to food?
V_foodperdose = 25*Strains*Reps*N_Bleaches*(1+(Excess_Percent/100))  # tested bleach  # Well mixture volume (worms, OD30, drug, diluent)
C_foodperwell = high_dose[i]*3 # 3X because drug is diluted 1:3 when fed to worms (50 uL/well)

#temp excess volume edit
temp_excess = 1.1

V_drugdilution = (V_foodperdose*.01)*temp_excess # ^ Volume of drug to add to OD30 mixture, added to make OD30 + 1% Diluent with Drug
C_drugdilution = (C_foodperwell * V_foodperdose)/(V_drugdilution/temp_excess)

###########
### When making serial dilutions for each drug, how much volume should be transferred between doses?
###########
# Transferred Volume = Fixed Volume/(Dilution Factor - 1) where:
# Fixed = Volume of drug added to OD30
# Transferred Volume = Volume transferred during serial dilution of high dose
V_transferred = V_drugdilution/(df[i] - 1)

###########
### How much of the drug at stock concentration should be added to diluent to make the high dose 
### from which all other doses will be diluted?
###########
V_Stock = ((C_drugdilution)*(V_drugdilution + V_transferred))/(stock[i]*1000) # stock (concentratio) here is in uM...
V_totaldiluent <- (V_drugdilution + V_transferred)-V_Stock
High_Dose_Table <- data.frame(rbind(V_Stock, V_totaldiluent))
options(scipen = 99999)
rownames(High_Dose_Table) <- c(paste("Volume of", stock[i], "mM", drug[i], "Stock",sep = " "), # stock concentration here is in mM
                               "Volume of Diluent")
colnames(High_Dose_Table) <- "Volume (uL)"
drugdilutiontable[[i]] <- High_Dose_Table

###########
### Print Tables of Drug Dilutions
###########
Doses <- c(high_dose[i])
for(d in 1:(N_Doses-2)){
  Doses[[d+1]] <- Doses[d]/df[i]
}
# Overview of Doses in Experiment
Final_Doses <- rev(c(Doses, 0))
# Diluent volume for each dose in serial dilution *not including high dose*
Diluent_Volume <- rep(V_drugdilution, N_Doses)
Diluent_Volume[N_Doses] <- NA
# Volume transferred between doses, beginning with highest dose
Transfer_Volume <- rep(V_transferred, N_Doses)
Transfer_Volume[N_Doses] <- NA
Transfer_Volume[1] <- NA
Dilution.Table <- data.frame(rbind(Final_Doses, 
                                   Diluent_Volume, 
                                   Transfer_Volume)
                                   )
colnames(Dilution.Table) <- paste("Dose",rep(1:N_Doses), sep = " ")
rownames(Dilution.Table) <- c("Final Dose in Well (uM)",
                              "Diluent Volume (uL)",
                              "Transfer Volume (uL)")
serialdilutiontable[[i]] <- Dilution.Table



Dose_Volume <- rep(V_drugdilution, N_Doses)
fooddosetable <- data.frame(rbind((Dose_Volume/temp_excess),
                                  (V_foodperdose-(Dose_Volume/temp_excess))
))
colnames(fooddosetable) <- paste("Dose",rep(1:N_Doses), sep = " ")
rownames(fooddosetable) <- c(paste(drug[i], "Dilution Volume to Add to OD30 (above)", sep = " "),
                             "OD30 (uL)")
fooddoses[[i]] <- fooddosetable

}

```

```{r, echo = FALSE, results='asis'}
looplist <- list(drug, drugdilutiontable, serialdilutiontable, fooddoses)
kable_loop <- function(w, x, y, z){
  #+ results='asis'
  print(w)
  print(knitr::kable(x, format = "markdown", digits = 3))
  print(knitr::kable(y, format = "markdown", digits = 3))
  print(knitr::kable(z, format = "markdown", digits = 3))
  cat("\n\n---------------------\n\n")
}
purrr::pmap(looplist, kable_loop) %>% compact()
```