---
title: "Serial Dilution and Feed Preparation"
subtitle: "`r params$assay`"
author: "Sam Widmayer"
params:
  date: "`r format(Sys.time(), '%d %B %Y')`"
  assay: "toxin16A"
output: 
  html_document:
    css: drug.dilution.style.css
---

```{r setup, include=FALSE, echo=FALSE}
require(tidyverse)
require(RColorBrewer)
require(knitr)
require(kableExtra)
# opts_knit$set(root.dir=normalizePath('../'))
# setwd("~/Documents/projects/NemaDose/") # Set to repo directory
setwd("~/Documents/AndersenLab/NemaDose/") # Set to repo directory
options(knitr.table.format = "html") 
options(width = 10000)
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
compound.sheet <- read.csv("drug_stock_sheet.csv")
```

```{r echo=FALSE}
Strain.List = c("PD1074","CB4856","RC301","ECA248","MY16","ECA36","ECA396","XZ1516")
Strains = length(Strain.List)
Reps = 4
N_Doses = 12
N_Bleaches = 3
N_Wells = Strains*Reps*N_Doses*N_Bleaches
Excess_Percent = 10

########################################################
## Specify compounds of interest (remember spelling!) ##
########################################################
ChosenDrugList = c("Arsenic trioxide",
                   "Atrazine",
                   "Carbaryl",
                   "Carboxin",
                   "Chlorpyrifos",
                   "Lead(II) nitrate")
pre.DrugList <- compound.sheet %>%
  dplyr::select(Drug, DilutionFactors) %>%
  dplyr::filter(Drug %in% ChosenDrugList)
DrugList <- as.vector(pre.DrugList$Drug)
DilutionFactors = as.vector(pre.DrugList$DilutionFactors)
#####

##############################################################
## Read in highest dosing concentration from compound sheet ##
##############################################################
pre.HighDoseList <- compound.sheet %>%
  dplyr::filter(Drug %in% ChosenDrugList) %>%
  dplyr::select(High_Dose_uM)
High_Dose_List_uM <- as.vector(pre.HighDoseList$High_Dose_uM)
#####

##########################################################
## Read in drug stock concentration from compound sheet ##
##########################################################
pre.StockList <- compound.sheet %>%
  dplyr::filter(Drug %in% ChosenDrugList) %>%
  dplyr::select(Drug_Stock_Concentration_mM)
Drug_Stock_Concentration_mM <- as.vector(pre.StockList$Drug_Stock_Concentration_mM)
#####


Drugs = length(DrugList)
DrugDilutionList <- list(DrugList,
                         High_Dose_List_uM, 
                         Drug_Stock_Concentration_mM, 
                         DilutionFactors)
OD30totalvolume <- N_Wells*Drugs*25*(1+(Excess_Percent/100))
OD100totalvolume <- OD30totalvolume*0.3 #uL
n_conicals <- round(OD100totalvolume*0.001/7.5, digits = 0) # mL
n_microcentrifuge <- ((OD100totalvolume*0.001/7.5) - round(OD100totalvolume*0.001/7.5, digits = 0))/0.8 # ? not clear to Tim C. 20200611 are these 800 uL?
n_microcentrifuge_test <- OD100totalvolume - n_conicals*7500
n_microcentrifuge <- ifelse(n_microcentrifuge < 0, 0, n_microcentrifuge)
```
### Experimental Factors:
#### ```r N_Bleaches``` Independent Bleach(es)
#### ```r Strains``` Strain(s): ```r Strain.List```
#### ```r N_Doses``` Doses of ```r Drugs``` Compounds
#### ```r Reps``` Replicates of each Dose per Strain
#### ```r Excess_Percent```% Excess Accounted for in Design

#### Chosen Dilution Factors:
```{r echo=FALSE}
df.dat <- data.frame(DrugList, DilutionFactors)
colnames(df.dat) <- c("Compound", "Dilution Factor")
df.dat %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(full_width = F, position = "left")
```

<!-- ### Experiment requires ```r n_conicals``` 15 mL conicals and ```r n_microcentrifuge``` microcentrifuge tubes of OD100 HB101.  -->
### Experiment requires ```r OD100totalvolume*0.001``` mL OD100 HB101.
#### OD30 Preparation
##### 1) Add ```r OD100totalvolume*0.001``` mL OD100 HB101 to sterile tube.
##### 2) Add ```r (OD100totalvolume*0.001)/0.3 - (OD100totalvolume*0.001)``` mL K-media to sterile tube.
##### 3) Add ```r (150*OD30totalvolume)/80000``` microliters 80 mM kanamycin stock to sterile tube.

```{r echo=FALSE}
drug <- DrugList
high_dose <- High_Dose_List_uM
stock <- Drug_Stock_Concentration_mM
df <- DilutionFactors

drugdilutiontable <- list()
serialdilutiontable <- list()
fooddoses <- list()

for(i in 1:length(drug)){
## At what concentration should the drug be added to food?
# V_foodperdose = 25*Strains*Reps*N_Bleaches*1.05 # 5% less excess for dose compared to total prep
V_foodperdose = 25*Strains*Reps*N_Bleaches*(1.05) # 09A: used same extra percentage for dose as total food prep
C_foodperwell = high_dose[i]*3 # 3X because drug is diluted 1:3 when fed to worms (50 uL/well) MICROMOLAR

V_drugdilution = (V_foodperdose*.01)  # ^ Volume of drug to add to OD30 mixture, added to make OD30 + 1% Diluent with Drug
C_drugdilution = (C_foodperwell * V_foodperdose)/(V_drugdilution) # MICROMOLAR

###########
### When making serial dilutions for each drug, how much volume should be transferred between doses?
###########
# Transferred Volume = Fixed Volume/(Dilution Factor - 1) where:
# Fixed = Volume of drug added to OD30
# Transferred Volume = Volume transferred during serial dilution of high dose
V_transferred = V_drugdilution/(df[i] - 1)

###########
### How much of the drug at stock concentration should be added to diluent to make the high dose 
### from which all other doses will be diluted?
###########
V_Stock = ((C_drugdilution)*(V_drugdilution + V_transferred))/(stock[i]*1000) # stock (concentratio) here is in MICROMOLAR AFTER X1000...
V_totaldiluent <- (V_drugdilution + V_transferred)-V_Stock
High_Dose_Table <- data.frame(rbind(V_Stock, V_totaldiluent))
options(scipen = 99999)
rownames(High_Dose_Table) <- c(paste("Volume of", stock[i], "mM", drug[i], "Stock",sep = " "), # stock concentration here is in mM
                               "Volume of Diluent")
colnames(High_Dose_Table) <- "Volume (uL)"
drugdilutiontable[[i]] <- High_Dose_Table

###########
### Print Tables of Drug Dilutions
###########
Doses <- c(high_dose[i])
for(d in 1:(N_Doses-2)){
  Doses[[d+1]] <- Doses[d]/df[i]
}
# Overview of Doses in Experiment
Final_Doses <- rev(c(Doses, 0))
# Diluent volume for each dose in serial dilution *not including high dose*
Diluent_Volume <- rep(V_drugdilution, N_Doses)
Diluent_Volume[N_Doses] <- NA
# Volume transferred between doses, beginning with highest dose
Transfer_Volume <- rep(V_transferred, N_Doses)
Transfer_Volume[N_Doses] <- NA
Transfer_Volume[1] <- NA
Dilution.Table <- data.frame(rbind(Final_Doses, 
                                   Diluent_Volume, 
                                   Transfer_Volume)
                                   )
colnames(Dilution.Table) <- paste("Dose",rep(1:N_Doses), sep = " ")
rownames(Dilution.Table) <- c("Final Dose in Well (uM)",
                              "Diluent Volume (uL)",
                              "Transfer Volume (uL)")
serialdilutiontable[[i]] <- Dilution.Table
Dose_Volume <- rep(V_drugdilution, N_Doses)
fooddosetable <- data.frame(rbind((Dose_Volume),
                                  (V_foodperdose-(Dose_Volume))
))
colnames(fooddosetable) <- paste("Dose",rep(1:N_Doses), sep = " ")
rownames(fooddosetable) <- c(paste(drug[i], "Dilution Volume to Add to OD30 (above)", sep = " "),
                             "OD30 (uL)")
fooddoses[[i]] <- fooddosetable

}

```

```{r, echo = FALSE, results='asis'}
looplist <- list(drug, drugdilutiontable, serialdilutiontable, fooddoses)
kable_loop <- function(w, x, y, z){
  #+ results='asis'
  print(w)
  print(knitr::kable(x, format = "markdown", digits = 3))
  print(knitr::kable(y, format = "markdown", digits = 3))
  print(knitr::kable(z, format = "markdown", digits = 3))
  cat("\n\n---------------------\n\n")
}
purrr::pmap(looplist, kable_loop) %>% compact()
```


```{r eval=FALSE, message=TRUE, warning=TRUE, include=FALSE}
# Constants
assay_type <- "48h"
food_conc_OD <- 10
food_type <- "15hHB101_20200127"
diluent_concentration_perc <- "1"
drug_prep_method <- "serial; Rscript"

# Strains
strains.df <- t(data.frame(Strain.List))
strain.prefix <- "Strain"; strain.suffix <- seq(1:Strains)
colnames(strains.df) <- paste(strain.prefix, strain.suffix, sep = "_")
# Reps
rep.df <- t(data.frame(seq(1:Reps)))
rep.prefix <- "Rep"; rep.suffix <- seq(1:Reps)
colnames(rep.df) <- paste(rep.prefix, rep.suffix, sep = "_")
# Bleaches
bleach.df <- t(data.frame(seq(1:N_Bleaches)))
bleach.prefix <- "bleach"; bleach.suffix <- seq(1:N_Bleaches)
colnames(bleach.df) <- paste(bleach.prefix, bleach.suffix, sep = "_")

# Combining
drug.dose.list <- list()
for(i in 1:length(drug)){
  doses <- data.frame(serialdilutiontable[i])
  drug.doses <- data.frame(drug[i], doses[1,])
  colnames(drug.doses) <- c("drug",colnames(drug.doses)[-1])
  rownames(drug.doses) <- i
  drug.dose.list[[i]] <- cbind(drug.doses,strains.df) %>%
    cbind(.,rep.df) %>%
    cbind(.,bleach.df) %>%
    dplyr::mutate(assay_type = assay_type,
                  food_conc_OD = food_conc_OD,
                  food_type = food_type,
                  diluent_concentration_perc = diluent_concentration_perc,
                  drug_prep_method = drug_prep_method)
}
drug.dose.df <- do.call(rbind, drug.dose.list)
diluent <- compound.sheet %>%
  dplyr::select(Drug, diluent, drug_stock_prep_date) %>%
  dplyr::rename(drug = Drug)
# 8 Strain Design --> Other groupings possible but not explored so far
prelim.design <- drug.dose.df %>%
  dplyr::left_join(., diluent) %>%
  dplyr::arrange(diluent) %>%
  tidyr::pivot_longer(cols = contains("Strain"), names_to = "strain.cat", values_to = "strain") %>% # strains
  tidyr::pivot_longer(cols = contains("Dose"), names_to = "dose.cat", values_to = "concentration_um") %>% # dose
  tidyr::pivot_longer(cols = contains("bleach"), names_to = "bleach.cat", values_to = "bleach") %>% # bleach
  tidyr::pivot_longer(cols = contains("Rep", ignore.case = F), names_to = "rep.cat", values_to = "replicate") %>% # reps
  dplyr::select(assay_type, food_conc_OD, food_type, diluent, drug, concentration_um, strain, bleach, diluent_concentration_perc, drug_stock_prep_date, drug_prep_method, replicate) %>%
  dplyr::group_by(drug, bleach, replicate) %>%
  tidyr::nest()

design.plates <- list()
for(i in 1:length(prelim.design$data)){
  x  <- prelim.design$data[[i]] %>%
    dplyr::group_by(strain) %>%
    tidyr::nest()
  rows <- c("A","B","C","D","E","F","G","H")
  
  plates <- list()
  for(j in 1:length(x$data)){
    y <- x$data[[j]] %>%
      dplyr::mutate(well.num = seq(1:nrow(.)),
                    strain = x$strain[[j]])
    if(j > 8){
      y$row <- rows[j%%8]
    } else {
        y$row <- rows[j]
    }
    y$Metadata_Well <- sprintf(paste(y$row,"%02d",sep = ""), y$well.num)
    plates[[j]] <- y 
  }
  
  
  plate.prelim <- do.call(rbind, plates) %>%
    dplyr::mutate(drug = prelim.design$drug[[i]],
                  bleach = prelim.design$bleach[[i]],
                  Metadata_Plate = sprintf("p%02d", i))
  design.plates[[i]] <- plate.prelim %>%
    dplyr::select(Metadata_Plate,Metadata_Well,assay_type,food_conc_OD,food_type,diluent,drug,concentration_um,strain,bleach,
                  diluent_concentration_perc,drug_stock_prep_date,drug_prep_method, well.num, row) %>% 
    dplyr::mutate(well_censor = "",
                  well_censor_reason = "",
                  notes = "")
}
design.df <- do.call(rbind, design.plates) 

# Write Design File
setwd("~/Documents/projects/NemaDose/")
today <- format(Sys.time(), '%Y%m%d')
design.df %>%
  dplyr::select(-row, -well.num) %>%
  write.csv(., paste(today, params$assay, "design.csv", sep = "_"), row.names = F, quote = F)

plot.design.df <- design.df %>%
  dplyr::mutate(row = as.factor(row)) %>%
  dplyr::mutate(well.num = as.factor(well.num)) %>%
  droplevels()
```

```{r eval=FALSE, fig.height=8, fig.width=12, message=FALSE, warning=FALSE, include=FALSE, paged.print=TRUE, results='asis'}
strain.table <- plot.design.df %>%
  dplyr::group_by(strain, row) %>%
  dplyr::summarise(n()) %>%
  dplyr::arrange(strain) %>%
  dplyr::select(-`n()`)
print(knitr::kable(strain.table, format = "markdown", digits = 3))
plot.design.df$row <- factor(plot.design.df$row, levels = rev(levels(plot.design.df$row)))
ggplot(plot.design.df, mapping = aes(x = well.num, y = row, fill = strain, alpha = log(concentration_um))) + 
  theme_minimal() + 
  geom_tile() + 
  facet_wrap(.~Metadata_Plate) +
  scale_fill_brewer(name = "Strain", palette = "Spectral") + 
  # theme(axis.text = element_blank(),
  #       axis.ticks = element_blank(),
  #       axis.title = element_blank()) + 
  ggtitle("Assay Plates: Strain Layout")
```

```{r eval=FALSE, fig.height=8, fig.width=12, message=FALSE, warning=FALSE, include=FALSE, paged.print=TRUE, results='asis'}
drug.table <- plot.design.df %>%
  dplyr::group_by(drug, Metadata_Plate) %>%
  dplyr::summarise(n()) %>%
  dplyr::arrange(Metadata_Plate) %>%
  dplyr::select(-`n()`)
print(knitr::kable(drug.table, format = "markdown", digits = 3))
plot.design.df %>%
  dplyr::mutate(plate.label = paste(Metadata_Plate, drug, sep = ": ")) %>%
  dplyr::arrange(Metadata_Plate) %>%
  ggplot(., mapping = aes(x = well.num, y = row, fill = drug, alpha = log(concentration_um))) + 
  theme_minimal() + 
  geom_tile() + 
  facet_wrap(.~plate.label) +
  scale_fill_brewer(name = "Drug", palette = "Set3") + 
  # theme(axis.text = element_blank(),
  #       axis.ticks = element_blank(),
  #       axis.title = element_blank()) + 
  ggtitle("Assay Plates: Drug Layout")
```





